# Generated by Django 5.2.7 on 2026-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0055_remove_vendor_vps_score_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproof',
            name='description',
            field=models.TextField(blank=True, help_text='Notes or context about this proof'),
        ),
        migrations.AddField(
            model_name='purchaseorderproof',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
