# Generated by Django 5.2.7 on 2026-03-15 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0056_purchaseorderproof_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_bleed_mm', models.DecimalField(decimal_places=1, default=3.0, max_digits=5)),
                ('default_safe_zone_mm', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('default_min_dpi', models.IntegerField(default=300)),
                ('default_color_profile', models.CharField(choices=[('cmyk', 'CMYK (Print Standard)'), ('rgb', 'RGB (Digital)'), ('pantone', 'Pantone Spot Colors'), ('cmyk_pantone', 'CMYK + Pantone')], default='cmyk', max_length=20)),
                ('default_production_method', models.CharField(choices=[('digital_offset', 'Digital Offset Printing'), ('offset', 'Offset Printing'), ('screen', 'Screen Printing'), ('digital', 'Digital Printing'), ('large_format', 'Large Format Printing'), ('embroidery', 'Embroidery'), ('sublimation', 'Sublimation'), ('laser_engraving', 'Laser Engraving'), ('uv_printing', 'UV Printing'), ('other', 'Other')], default='digital_offset', max_length=50)),
            ],
            options={
                'verbose_name': 'Print Category',
                'verbose_name_plural': 'Print Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='associated_variable',
        ),
        migrations.RemoveField(
            model_name='materialinventory',
            name='product_variable_option',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='associated_option',
        ),
        migrations.AlterModelOptions(
            name='productapprovalrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Product Approval Request', 'verbose_name_plural': 'Product Approval Requests'},
        ),
        migrations.AlterModelOptions(
            name='productchangehistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Product Change History', 'verbose_name_plural': 'Product Change History'},
        ),
        migrations.AlterModelOptions(
            name='productdownloadablefile',
            options={'ordering': ['product', 'display_order'], 'verbose_name': 'Downloadable File'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product', 'display_order'], 'verbose_name': 'Product Image'},
        ),
        migrations.AlterModelOptions(
            name='productlegal',
            options={'verbose_name': 'Product Legal', 'verbose_name_plural': 'Product Legal'},
        ),
        migrations.AlterModelOptions(
            name='productmateriallink',
            options={'ordering': ['product', 'material_type'], 'verbose_name': 'Product–Material Link', 'verbose_name_plural': 'Product–Material Links'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Review'},
        ),
        migrations.AlterModelOptions(
            name='productreviewsettings',
            options={'verbose_name': 'Product Review Settings', 'verbose_name_plural': 'Product Review Settings'},
        ),
        migrations.AlterModelOptions(
            name='productshipping',
            options={'verbose_name': 'Product Shipping', 'verbose_name_plural': 'Product Shipping'},
        ),
        migrations.AlterModelOptions(
            name='producttemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Template'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['product', 'display_order'], 'verbose_name': 'Product Video'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customization_level',
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('auto_calculate', 'Auto Calculate'), ('quote_only', 'Quote Only')], default='auto_calculate', help_text='auto_calculate: storefront computes price live from spec groups. quote_only: Production Team must manually price each request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_created', 'New Lead Created'), ('quote_reminder', 'Quote Creation Reminder'), ('quote_approved', 'Quote Approved by Client'), ('quote_sent_pt', 'Quote Sent to PT for Approval'), ('quote_pt_approved', 'Quote Costed by PT'), ('quote_discount_request', 'Price Reduction Requested'), ('quote_adjustment_request', 'Quote Adjustments Requested'), ('convert_lead', 'Convert Lead to Client'), ('delivery_ready', 'Delivery Ready for AM'), ('job_completed', 'Job Completed'), ('vendor_proof_uploaded', 'Vendor Proof Uploaded'), ('vendor_invoice_submitted', 'Vendor Invoice Submitted'), ('vendor_issue_raised', 'Vendor Issue Raised'), ('vendor_substitution_requested', 'Vendor Substitution Requested'), ('vendor_portal_invite_sent', 'Vendor Portal Invite Sent'), ('job_assigned', 'Job Assigned to Vendor'), ('general', 'General Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='maintenance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clientapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clientapp.productfamily'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order'), ('discontinued', 'Discontinued')], default='made_to_order', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clientapp.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure_custom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productapprovalrequest',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productapprovalrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approval_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productapprovalrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approval_requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productapprovalrequest',
            name='reason_for_change',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productapprovalrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approval_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productdownloadablefile',
            name='file_size',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productlegal',
            name='age_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmateriallink',
            name='quantity_per_product',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='accepts_transparency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bleed_mm',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bom_ink_coverage_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bom_primary_material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bom_primary_quantity_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bom_primary_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='bom_primary_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='color_profile',
            field=models.CharField(choices=[('cmyk', 'CMYK (Print Standard)'), ('rgb', 'RGB (Digital)'), ('pantone', 'Pantone Spot Colors'), ('cmyk_pantone', 'CMYK + Pantone')], default='cmyk', max_length=20),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='machine_equipment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='max_ink_coverage',
            field=models.IntegerField(default=280),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='min_resolution_dpi',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='production_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='requires_outlined_fonts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='safe_zone_mm',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productreviewsettings',
            name='auto_approve_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreviewsettings',
            name='require_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='additional_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='price_display_format',
            field=models.CharField(choices=[('from', 'From KES X'), ('starting', 'Starting at KES X'), ('plus', 'KES X+'), ('range', 'KES X – Y')], default='from', max_length=20),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productshipping',
            name='handling_time_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Business Days'), ('weeks', 'Weeks')], default='days', max_length=10),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='category_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='product',
            name='print_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clientapp.printcategory'),
        ),
        migrations.CreateModel(
            name='SpecGroupLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('quantity_tier', 'Quantity Tier'), ('single_select_modifier', 'Single Select Modifier'), ('multi_select_modifier', 'Multi Select Modifier'), ('numeric_input', 'Numeric Input'), ('dimension_input', 'Dimension Input (W × H)'), ('multiplier', 'Multiplier'), ('display_only', 'Display Only')], max_length=30)),
                ('display_label', models.CharField(blank=True, help_text='Customer-facing label. Defaults to name if blank.', max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spec Group Library',
                'verbose_name_plural': 'Spec Group Libraries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_library_options', models.BooleanField(default=False, help_text='When True, the storefront uses library options instead of product-level SpecOptions.')),
                ('name', models.CharField(max_length=150)),
                ('display_label', models.CharField(blank=True, max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('group_type', models.CharField(choices=[('quantity_tier', 'Quantity Tier'), ('single_select_modifier', 'Single Select Modifier'), ('multi_select_modifier', 'Multi Select Modifier'), ('numeric_input', 'Numeric Input'), ('dimension_input', 'Dimension Input (W × H)'), ('multiplier', 'Multiplier'), ('display_only', 'Display Only')], max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('dim_unit', models.CharField(blank=True, choices=[('mm', 'mm'), ('cm', 'cm'), ('in', 'inches')], default='mm', max_length=5)),
                ('dim_width_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_width_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_height_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_height_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_rate_per_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vendor_rate_per_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('min_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_vendor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='clientapp.product')),
                ('library_group', models.ForeignKey(blank=True, help_text='Link to a library group. Leave blank for a product-custom group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_usages', to='clientapp.specgrouplibrary')),
            ],
            options={
                'verbose_name': 'Product Spec Group',
                'ordering': ['product', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='printcategory',
            name='suggested_library_groups',
            field=models.ManyToManyField(blank=True, related_name='suggested_for_categories', to='clientapp.specgrouplibrary'),
        ),
        migrations.CreateModel(
            name='SpecGroupLibraryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_value', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price_modifier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_cost_modifier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('multiplier_value', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('library_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_options', to='clientapp.specgrouplibrary')),
            ],
            options={
                'verbose_name': 'Spec Group Library Option',
                'ordering': ['library_group', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_value', models.IntegerField(blank=True, help_text='The quantity this tier represents (e.g. 100, 500, 1000).', null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price_modifier', models.DecimalField(blank=True, decimal_places=2, help_text='Amount added to selling total when this option is selected.', max_digits=12, null=True)),
                ('vendor_cost_modifier', models.DecimalField(blank=True, decimal_places=2, help_text='Amount added to vendor cost when this option is selected.', max_digits=12, null=True)),
                ('multiplier_value', models.DecimalField(blank=True, decimal_places=4, help_text='Multiplied against the current subtotal (e.g. 1.50 = +50%).', max_digits=6, null=True)),
                ('library_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_option_overrides', to='clientapp.specgrouplibraryoption')),
                ('spec_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='clientapp.productspecgroup')),
            ],
            options={
                'verbose_name': 'Spec Option',
                'ordering': ['spec_group', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='productspecgroup',
            name='parent_option',
            field=models.ForeignKey(blank=True, help_text='Show this group only when the parent option is selected (conditional logic).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_spec_groups', to='clientapp.specoption'),
        ),
        migrations.CreateModel(
            name='ProductCompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('requires', 'Requires'), ('excludes', 'Excludes'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value')], max_length=20)),
                ('error_message', models.CharField(blank=True, help_text='Message shown to the customer when this rule is violated.', max_length=500)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_rules', to='clientapp.product')),
                ('condition_spec_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_rules', to='clientapp.productspecgroup')),
                ('target_spec_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='clientapp.productspecgroup')),
                ('condition_option', models.ForeignKey(blank=True, help_text='If null, the rule applies when any option in the condition group is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_rules', to='clientapp.specoption')),
                ('target_option', models.ForeignKey(blank=True, help_text='If null, the rule applies to any option in the target group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_rules', to='clientapp.specoption')),
            ],
            options={
                'verbose_name': 'Product Compatibility Rule',
                'ordering': ['product', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='spec_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='clientapp.specoption'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='associated_spec_option',
            field=models.ForeignKey(blank=True, help_text='Show this image only when the linked spec option is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='clientapp.specoption'),
        ),
        migrations.CreateModel(
            name='SpecOptionRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for open-ended upper bound.', max_digits=12, null=True)),
                ('unit_label', models.CharField(blank=True, help_text='e.g. "stitches", "meters".', max_length=50)),
                ('selling_price_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_rate_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vendor_cost_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_rate_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('display_order', models.IntegerField(default=0)),
                ('spec_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='clientapp.productspecgroup')),
            ],
            options={
                'verbose_name': 'Spec Option Range',
                'ordering': ['spec_group', 'display_order', 'range_from'],
            },
        ),
    ]
